# This is an example Mocha config containing every Mocha option plus others.
# https://github.com/mochajs/mocha/blob/main/example/config/.mocharc.yml

extension: ['ts']
spec:
  - 'tests/**/*.spec.ts' # the positional arguments!
require:
  - 'tsx'

recursive: true
