# This is an example Mocha config containing every Mocha option plus others.
# https://github.com/mochajs/mocha/blob/main/example/config/.mocharc.yml

extension: ['ts']
spec:
  - 'tests/testing.setup.ts'
  - 'tests/**/*.spec.ts' # the positional arguments!
require:
  - 'tsx'
  - 'mochawesome/register'
enable-source-maps: true
timeout: 2000
reporter: mochawesome
reporter-option:
  - 'reportDir=./reports/mochawesome'
  - 'consoleReporter=spec'
  - 'reportFilename=basic-database-testing-report'
recursive: true
